default['atlassian']['fisheye']['db_user'] = 'fisheye'
default['atlassian']['fisheye']['db_name'] = 'fisheye_db'
default['atlassian']['fisheye']['db_host'] = 'dbserver.example.com'
default['atlassian']['fisheye']['package'] = 'fisheye-3.6.2.zip'
default['atlassian']['fisheye']['remote_url'] = 'http://www.atlassian.com/software/fisheye/downloads/binary'
default['atlassian']['fisheye']['answers_file'] = ''
